version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: auto_rental_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "54321"
      POSTGRES_DB: AutoRental
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: auto_rental_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5052:80"
    depends_on:
      - postgres

  api:
    build:
      context: ..
      dockerfile: AutoRentalSystem.API/Dockerfile
    container_name: auto_rental_api
    ports:
      - "5003:5003"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=AutoRental;Username=postgres;Password=54321

  minio:
    image: minio/minio
    container_name: auto_rental_minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: secret123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # frontend:
  #   build:
  #     context: ../AutoRentalSystem.Frontend\autorentalsystem
  #     dockerfile: Dockerfile
  #   container_name: auto_rental_frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://api:5003
  #   restart: always

volumes:
  postgres_data_new:
  minio_data:
